require:
  - rubocop-minitest
  - rubocop-rake
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - Gemfile
    - Rakefile
    - db/schema.rb
    - ".git/**/*"
    - bin/*
    - db/migrate/*.rb
  TargetRubyVersion: 3.1.2
  SuggestExtensions: false

Layout/LineLength:
  Max: 170

Lint/DuplicateRequire:
  Enabled: true

Lint/EmptyFile:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Metrics/AbcSize:
  Max: 21

Metrics/MethodLength:
  Max: 20

Style/CombinableLoops:
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/KeywordParametersOrder:
  Enabled: true

Style/RedundantSelfAssignment:
  Enabled: true

Style/SoleNestedConditional:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
