name: CI
on:
  push:
  pull_request:
    branches: [master]

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [3.1.2]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run linters and security checks
        run: bin/quality
